language: android
jdk: oraclejdk8
dist: xenial
os: linux
env:
  global:
    - ANDROID_API_LEVEL=29
    - ANDROID_BUILD_TOOLS_VERSION=29.0.3
    - ANDROID_TARGET=android-22
    - ANDROID_ABI=armeabi-v7a

android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  components:
    - tools
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-$ANDROID_API_LEVEL
    - $ANDROID_TARGET
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_script:
  - cd app/
  - chmod +x gradlew

stages:
  - build
  - name: deploy
    if:  (branch = master) AND (NOT (type IN (push, pull_request)))

jobs:
  include:
    - stage: build
      script: 
      - ./gradlew build jacocoTestReport assembleAndroidTest
      - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
      - emulator -avd test -no-skin -no-audio -no-window &
      - android-wait-for-emulator
      - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
      - ./gradlew connectedCheck
      after_success:
      - bash <(curl -s https://codecov.io/bash)
    - stage: deploy
      deploy:
        provider: releases
        token: $GITHUB_API_KEY
        file: $TRAVIS_BUILD_DIR/app/build/outputs/apk/debug/app-debug.apk
        name: $TRAVIS_TAG
        release_notes: Automatic build of $TRAVIS_BRANCH ($TRAVIS_COMMIT) built by Travis CI on $(date +'%F %T %Z').
        overwrite: true
        cleanup: true
        on:
          tags: true
      after_deploy:
        - rm -rf $TRAVIS_BUILD_DIR/app/build/outputs